# 关节状态控制器
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - r_joint
    - l_joint
    - r_in_joint  
    - r_out_joint 
    - l_in_joint 
    - l_out_joint 

# 机械臂控制器保持不变
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  # 大幅降低PID参数
  gains:
    joint1: {p: 1, d: 0.0, i: 0, i_clamp: 0.0}
    joint2: {p: 0.5, d: 0.0, i: 0.1, i_clamp: 0.0}
    joint3: {p: 0.5, d: 0.0, i: 0.1, i_clamp: 0.0}
    joint4: {p: 1, d: 0.0, i: 0, i_clamp: 0.0}
    joint5: {p: 1, d: 0.0, i: 0, i_clamp: 0.0}
  # 更宽松的约束
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.5
    joint1: {trajectory: 0.5, goal: 0.5}
    joint2: {trajectory: 0.5, goal: 0.5}
    joint3: {trajectory: 0.5, goal: 0.5}
    joint4: {trajectory: 0.5, goal: 0.5}
    joint5: {trajectory: 0.5, goal: 0.5}
  stop_trajectory_duration: 1.0
  # 降低发布率
  state_publish_rate: 20
  action_monitor_rate: 5

# 夹爪控制器 - 增加PID增益

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints: ['r_joint', 'l_joint', 'r_in_joint', 'r_out_joint', 'l_in_joint', 'l_out_joint']
  gains:
    r_joint: {p: 0.5, i: 0.0, d: 0.01, i_clamp: 0.1}
    l_joint: {p: 0.5, i: 0.0, d: 0.01, i_clamp: 0.1}
    r_in_joint: {p: 0.01, i: 0.0, d: 0.0001, i_clamp: 0.0}
    r_out_joint: {p: 0.01, i: 0.0, d: 0.0001, i_clamp: 0.0}
    l_in_joint: {p: 0.01, i: 0.0, d: 0.0001, i_clamp: 0.0}
    l_out_joint: {p: 0.01, i: 0.0, d: 0.0001, i_clamp: 0.0}
  joint_limit_margin: 0.1
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.01
    r_joint: {trajectory: 0.2, goal: 0.2}
    l_joint: {trajectory: 0.2, goal: 0.2}
    r_in_joint: {trajectory: 0.2, goal: 0.2}
    r_out_joint: {trajectory: 0.2, goal: 0.2}
    l_in_joint: {trajectory: 0.2, goal: 0.2}
    l_out_joint: {trajectory: 0.2, goal: 0.2}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25


