# 关节状态控制器
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - r_joint
    - l_joint

# 机械臂控制器
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  # 大幅降低PID参数
  gains:
    joint1: {p: 10.0, d: 1.0, i: 0.0, i_clamp: 0.5}
    joint2: {p: 10.0, d: 1.0, i: 0.0, i_clamp: 0.5}
    joint3: {p: 5.0, d: 0.5, i: 0.0, i_clamp: 0.5}
    joint4: {p: 2.0, d: 0.2, i: 0.0, i_clamp: 0.5}
    joint5: {p: 2.0, d: 0.2, i: 0.0, i_clamp: 0.5}
  # 更宽松的约束
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.5
    joint1: {trajectory: 0.5, goal: 0.5}
    joint2: {trajectory: 0.5, goal: 0.5}
    joint3: {trajectory: 0.5, goal: 0.5}
    joint4: {trajectory: 0.5, goal: 0.5}
    joint5: {trajectory: 0.5, goal: 0.5}
  stop_trajectory_duration: 1.0
  # 降低发布率
  state_publish_rate: 20
  action_monitor_rate: 5

# 夹爪控制器
gripper_controller:
  type: effort_controllers/JointPositionController
  joint: r_joint
  # 极低的PID参数
  pid: {p: 1.0, i: 0.0, d: 0.5}

