# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gripper
  joint_model_group_pose: close

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - r_joint
  
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05

  gains:
    joint1: {p: 100.0, i: 0.0, d: 10.0}
    joint2: {p: 100.0, i: 0.0, d: 10.0}
    joint3: {p: 100.0, i: 0.0, d: 10.0}
    joint4: {p: 100.0, i: 0.0, d: 10.0}
    joint5: {p: 100.0, i: 0.0, d: 10.0}

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
  gains:
    r_joint: {p: 50.0, i: 0.0, d: 5.0}

controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - r_joint
  
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

